# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './GUI/Design.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1363, 1105)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.label_19 = QtWidgets.QLabel(self.tab)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 9, 1, 2, 1)
        self.convert_selected_images = QtWidgets.QPushButton(self.tab)
        self.convert_selected_images.setObjectName("convert_selected_images")
        self.gridLayout.addWidget(self.convert_selected_images, 7, 2, 2, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 1, 1, 2)
        self.interpolation_alg_centering = QtWidgets.QComboBox(self.tab)
        self.interpolation_alg_centering.setObjectName("interpolation_alg_centering")
        self.interpolation_alg_centering.addItem("")
        self.interpolation_alg_centering.addItem("")
        self.interpolation_alg_centering.addItem("")
        self.interpolation_alg_centering.addItem("")
        self.interpolation_alg_centering.addItem("")
        self.interpolation_alg_centering.addItem("")
        self.interpolation_alg_centering.addItem("")
        self.gridLayout.addWidget(self.interpolation_alg_centering, 9, 2, 2, 1)
        self.use_i607 = QtWidgets.QRadioButton(self.tab)
        self.use_i607.setChecked(True)
        self.use_i607.setObjectName("use_i607")
        self.gridLayout.addWidget(self.use_i607, 7, 1, 1, 1)
        self.use_i203 = QtWidgets.QRadioButton(self.tab)
        self.use_i203.setObjectName("use_i203")
        self.gridLayout.addWidget(self.use_i203, 8, 1, 1, 1)
        self.picture_dir_tree = QtWidgets.QTreeWidget(self.tab)
        self.picture_dir_tree.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.picture_dir_tree.setIconSize(QtCore.QSize(35, 35))
        self.picture_dir_tree.setObjectName("picture_dir_tree")
        self.picture_dir_tree.headerItem().setText(0, "Choose one or multiple image files for calibration tests:")
        self.gridLayout.addWidget(self.picture_dir_tree, 0, 0, 11, 1)
        self.change_image_directory = QtWidgets.QPushButton(self.tab)
        self.change_image_directory.setObjectName("change_image_directory")
        self.gridLayout.addWidget(self.change_image_directory, 1, 1, 1, 1)
        self.image_directory = QtWidgets.QLineEdit(self.tab)
        self.image_directory.setReadOnly(True)
        self.image_directory.setObjectName("image_directory")
        self.gridLayout.addWidget(self.image_directory, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 1, 1, 1)
        self.change_output_directory = QtWidgets.QPushButton(self.tab)
        self.change_output_directory.setObjectName("change_output_directory")
        self.gridLayout.addWidget(self.change_output_directory, 4, 1, 1, 1)
        self.output_directory = QtWidgets.QLineEdit(self.tab)
        self.output_directory.setText("")
        self.output_directory.setReadOnly(True)
        self.output_directory.setObjectName("output_directory")
        self.gridLayout.addWidget(self.output_directory, 4, 2, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_8.setMinimumSize(QtCore.QSize(0, 120))
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_8)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 0, 4, 1, 1)
        self.use_converted_i607 = QtWidgets.QRadioButton(self.groupBox_8)
        self.use_converted_i607.setChecked(True)
        self.use_converted_i607.setObjectName("use_converted_i607")
        self.buttonGroup_8 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_8.setObjectName("buttonGroup_8")
        self.buttonGroup_8.addButton(self.use_converted_i607)
        self.gridLayout_6.addWidget(self.use_converted_i607, 1, 4, 1, 1)
        self.show_plots = QtWidgets.QRadioButton(self.groupBox_8)
        self.show_plots.setMaximumSize(QtCore.QSize(300, 16777215))
        self.show_plots.setAutoExclusive(False)
        self.show_plots.setObjectName("show_plots")
        self.gridLayout_6.addWidget(self.show_plots, 1, 0, 2, 1)
        self.output_plots = QtWidgets.QRadioButton(self.groupBox_8)
        self.output_plots.setChecked(True)
        self.output_plots.setAutoExclusive(False)
        self.output_plots.setObjectName("output_plots")
        self.gridLayout_6.addWidget(self.output_plots, 0, 0, 1, 1)
        self.use_current_images = QtWidgets.QRadioButton(self.groupBox_8)
        self.use_current_images.setChecked(False)
        self.use_current_images.setObjectName("use_current_images")
        self.buttonGroup_8.addButton(self.use_current_images)
        self.gridLayout_6.addWidget(self.use_current_images, 0, 1, 3, 1)
        self.use_converted_i203 = QtWidgets.QRadioButton(self.groupBox_8)
        self.use_converted_i203.setObjectName("use_converted_i203")
        self.buttonGroup_8.addButton(self.use_converted_i203)
        self.gridLayout_6.addWidget(self.use_converted_i203, 2, 4, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_8, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setObjectName("label_14")
        self.gridLayout_7.addWidget(self.label_14, 0, 0, 1, 2)
        self.initial_guess_delta_rad = QtWidgets.QLineEdit(self.groupBox)
        self.initial_guess_delta_rad.setMaximumSize(QtCore.QSize(100, 16777215))
        self.initial_guess_delta_rad.setObjectName("initial_guess_delta_rad")
        self.gridLayout_7.addWidget(self.initial_guess_delta_rad, 2, 1, 2, 1, QtCore.Qt.AlignLeft)
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setObjectName("label_18")
        self.gridLayout_7.addWidget(self.label_18, 4, 0, 1, 2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.ange_step_label = QtWidgets.QLabel(self.groupBox_3)
        self.ange_step_label.setObjectName("ange_step_label")
        self.gridLayout_8.addWidget(self.ange_step_label, 1, 0, 1, 2)
        self.zoom1_ratio = QtWidgets.QLineEdit(self.groupBox_3)
        self.zoom1_ratio.setObjectName("zoom1_ratio")
        self.gridLayout_8.addWidget(self.zoom1_ratio, 4, 3, 1, 2)
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_8.addWidget(self.label_11, 5, 0, 1, 3)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_8.addWidget(self.label_9, 3, 0, 1, 2)
        self.angle_step_1_pix = QtWidgets.QLineEdit(self.groupBox_3)
        self.angle_step_1_pix.setObjectName("angle_step_1_pix")
        self.gridLayout_8.addWidget(self.angle_step_1_pix, 1, 2, 1, 2)
        self.zoom2_ratio = QtWidgets.QLineEdit(self.groupBox_3)
        self.zoom2_ratio.setObjectName("zoom2_ratio")
        self.gridLayout_8.addWidget(self.zoom2_ratio, 5, 3, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_8.addWidget(self.label_8, 2, 0, 1, 2)
        self.angle_step_1_rad = QtWidgets.QLineEdit(self.groupBox_3)
        self.angle_step_1_rad.setObjectName("angle_step_1_rad")
        self.gridLayout_8.addWidget(self.angle_step_1_rad, 1, 4, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_8.addWidget(self.label_10, 4, 0, 1, 3)
        self.label_42 = QtWidgets.QLabel(self.groupBox_3)
        self.label_42.setObjectName("label_42")
        self.gridLayout_8.addWidget(self.label_42, 0, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.angle_step_2_pix = QtWidgets.QLineEdit(self.groupBox_3)
        self.angle_step_2_pix.setObjectName("angle_step_2_pix")
        self.gridLayout_8.addWidget(self.angle_step_2_pix, 2, 2, 1, 2)
        self.angle_step_3_rad = QtWidgets.QLineEdit(self.groupBox_3)
        self.angle_step_3_rad.setObjectName("angle_step_3_rad")
        self.gridLayout_8.addWidget(self.angle_step_3_rad, 3, 4, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.groupBox_3)
        self.label_46.setObjectName("label_46")
        self.gridLayout_8.addWidget(self.label_46, 0, 1, 1, 3, QtCore.Qt.AlignHCenter)
        self.angle_step_3_pix = QtWidgets.QLineEdit(self.groupBox_3)
        self.angle_step_3_pix.setObjectName("angle_step_3_pix")
        self.gridLayout_8.addWidget(self.angle_step_3_pix, 3, 2, 1, 2)
        self.angle_step_2_rad = QtWidgets.QLineEdit(self.groupBox_3)
        self.angle_step_2_rad.setObjectName("angle_step_2_rad")
        self.gridLayout_8.addWidget(self.angle_step_2_rad, 2, 4, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.groupBox_3)
        self.label_54.setObjectName("label_54")
        self.gridLayout_8.addWidget(self.label_54, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_3, 0, 4, 11, 1)
        self.brute = QtWidgets.QRadioButton(self.groupBox)
        self.brute.setObjectName("brute")
        self.gridLayout_7.addWidget(self.brute, 8, 0, 1, 1)
        self.interpolation_alg_opt = QtWidgets.QComboBox(self.groupBox)
        self.interpolation_alg_opt.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.interpolation_alg_opt.setObjectName("interpolation_alg_opt")
        self.interpolation_alg_opt.addItem("")
        self.interpolation_alg_opt.addItem("")
        self.interpolation_alg_opt.addItem("")
        self.interpolation_alg_opt.addItem("")
        self.interpolation_alg_opt.addItem("")
        self.interpolation_alg_opt.addItem("")
        self.interpolation_alg_opt.addItem("")
        self.gridLayout_7.addWidget(self.interpolation_alg_opt, 5, 0, 2, 2)
        self.initial_guess_delta_pix = QtWidgets.QLineEdit(self.groupBox)
        self.initial_guess_delta_pix.setMaximumSize(QtCore.QSize(100, 16777215))
        self.initial_guess_delta_pix.setObjectName("initial_guess_delta_pix")
        self.gridLayout_7.addWidget(self.initial_guess_delta_pix, 2, 0, 2, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 7, 0, 1, 1)
        self.quadratic = QtWidgets.QRadioButton(self.groupBox)
        self.quadratic.setChecked(True)
        self.quadratic.setObjectName("quadratic")
        self.gridLayout_7.addWidget(self.quadratic, 10, 0, 2, 1)
        self.label_59 = QtWidgets.QLabel(self.groupBox)
        self.label_59.setObjectName("label_59")
        self.gridLayout_7.addWidget(self.label_59, 1, 1, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.groupBox)
        self.label_60.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_60.setObjectName("label_60")
        self.gridLayout_7.addWidget(self.label_60, 1, 0, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_62 = QtWidgets.QLabel(self.groupBox_7)
        self.label_62.setObjectName("label_62")
        self.gridLayout_9.addWidget(self.label_62, 0, 0, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.groupBox_7)
        self.label_55.setObjectName("label_55")
        self.gridLayout_9.addWidget(self.label_55, 0, 1, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.groupBox_7)
        self.label_56.setObjectName("label_56")
        self.gridLayout_9.addWidget(self.label_56, 0, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_7)
        self.label_15.setObjectName("label_15")
        self.gridLayout_9.addWidget(self.label_15, 1, 0, 1, 1)
        self.precision_quad_pix = QtWidgets.QLineEdit(self.groupBox_7)
        self.precision_quad_pix.setObjectName("precision_quad_pix")
        self.gridLayout_9.addWidget(self.precision_quad_pix, 1, 1, 1, 1)
        self.precision_quad_rad = QtWidgets.QLineEdit(self.groupBox_7)
        self.precision_quad_rad.setObjectName("precision_quad_rad")
        self.gridLayout_9.addWidget(self.precision_quad_rad, 1, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_7)
        self.label_16.setObjectName("label_16")
        self.gridLayout_9.addWidget(self.label_16, 2, 0, 1, 1)
        self.max_it_quad = QtWidgets.QLineEdit(self.groupBox_7)
        self.max_it_quad.setObjectName("max_it_quad")
        self.gridLayout_9.addWidget(self.max_it_quad, 2, 1, 1, 2)
        self.label_21 = QtWidgets.QLabel(self.groupBox_7)
        self.label_21.setObjectName("label_21")
        self.gridLayout_9.addWidget(self.label_21, 3, 0, 1, 1)
        self.cost_tolerance_quad = QtWidgets.QLineEdit(self.groupBox_7)
        self.cost_tolerance_quad.setObjectName("cost_tolerance_quad")
        self.gridLayout_9.addWidget(self.cost_tolerance_quad, 3, 1, 1, 2)
        self.gridLayout_7.addWidget(self.groupBox_7, 0, 5, 6, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_63 = QtWidgets.QLabel(self.groupBox_2)
        self.label_63.setObjectName("label_63")
        self.gridLayout_10.addWidget(self.label_63, 0, 0, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.groupBox_2)
        self.label_57.setObjectName("label_57")
        self.gridLayout_10.addWidget(self.label_57, 0, 1, 1, 2)
        self.label_58 = QtWidgets.QLabel(self.groupBox_2)
        self.label_58.setObjectName("label_58")
        self.gridLayout_10.addWidget(self.label_58, 0, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_10.addWidget(self.label_12, 1, 0, 1, 1)
        self.precision_fib_pix = QtWidgets.QLineEdit(self.groupBox_2)
        self.precision_fib_pix.setObjectName("precision_fib_pix")
        self.gridLayout_10.addWidget(self.precision_fib_pix, 1, 1, 1, 2)
        self.precision_fib_rad = QtWidgets.QLineEdit(self.groupBox_2)
        self.precision_fib_rad.setObjectName("precision_fib_rad")
        self.gridLayout_10.addWidget(self.precision_fib_rad, 1, 3, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_10.addWidget(self.label_17, 2, 0, 1, 2)
        self.max_points_fib = QtWidgets.QLineEdit(self.groupBox_2)
        self.max_points_fib.setObjectName("max_points_fib")
        self.gridLayout_10.addWidget(self.max_points_fib, 2, 2, 1, 2)
        self.label_20 = QtWidgets.QLabel(self.groupBox_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_10.addWidget(self.label_20, 3, 0, 1, 2)
        self.cost_tolerance_fib = QtWidgets.QLineEdit(self.groupBox_2)
        self.cost_tolerance_fib.setObjectName("cost_tolerance_fib")
        self.gridLayout_10.addWidget(self.cost_tolerance_fib, 3, 2, 1, 2)
        self.gridLayout_7.addWidget(self.groupBox_2, 6, 5, 6, 1)
        self.fibonacci = QtWidgets.QRadioButton(self.groupBox)
        self.fibonacci.setChecked(False)
        self.fibonacci.setObjectName("fibonacci")
        self.gridLayout_7.addWidget(self.fibonacci, 9, 0, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox, 2, 0, 1, 1)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_2.setMaximumSize(QtCore.QSize(16777215, 170))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_64 = QtWidgets.QLabel(self.tab_3)
        self.label_64.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_64.setObjectName("label_64")
        self.gridLayout_2.addWidget(self.label_64, 0, 3, 1, 1)
        self.max_rad_G = QtWidgets.QLineEdit(self.tab_3)
        self.max_rad_G.setMaximumSize(QtCore.QSize(200, 16777215))
        self.max_rad_G.setObjectName("max_rad_G")
        self.gridLayout_2.addWidget(self.max_rad_G, 0, 4, 1, 1)
        self.min_rad_G = QtWidgets.QLineEdit(self.tab_3)
        self.min_rad_G.setMaximumSize(QtCore.QSize(200, 16777215))
        self.min_rad_G.setObjectName("min_rad_G")
        self.gridLayout_2.addWidget(self.min_rad_G, 0, 2, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.tab_3)
        self.label_65.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_65.setObjectName("label_65")
        self.gridLayout_2.addWidget(self.label_65, 0, 1, 1, 1)
        self.use_exact_grav_G = QtWidgets.QRadioButton(self.tab_3)
        self.use_exact_grav_G.setChecked(True)
        self.use_exact_grav_G.setObjectName("use_exact_grav_G")
        self.gridLayout_2.addWidget(self.use_exact_grav_G, 0, 0, 1, 1)
        self.use_image_center_G = QtWidgets.QRadioButton(self.tab_3)
        self.use_image_center_G.setObjectName("use_image_center_G")
        self.gridLayout_2.addWidget(self.use_image_center_G, 1, 0, 1, 1)
        self.run_gradient_algorithm = QtWidgets.QPushButton(self.tab_3)
        self.run_gradient_algorithm.setObjectName("run_gradient_algorithm")
        self.gridLayout_2.addWidget(self.run_gradient_algorithm, 1, 2, 1, 3)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.use_exact_grav_R = QtWidgets.QRadioButton(self.tab_4)
        self.use_exact_grav_R.setChecked(True)
        self.use_exact_grav_R.setObjectName("use_exact_grav_R")
        self.buttonGroup_4 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_4.setObjectName("buttonGroup_4")
        self.buttonGroup_4.addButton(self.use_exact_grav_R)
        self.gridLayout_3.addWidget(self.use_exact_grav_R, 0, 0, 1, 1)
        self.use_image_center_R = QtWidgets.QRadioButton(self.tab_4)
        self.use_image_center_R.setObjectName("use_image_center_R")
        self.buttonGroup_4.addButton(self.use_image_center_R)
        self.gridLayout_3.addWidget(self.use_image_center_R, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 2, 1, 1)
        self.theta_min_R = QtWidgets.QLineEdit(self.tab_4)
        self.theta_min_R.setMaximumSize(QtCore.QSize(200, 16777215))
        self.theta_min_R.setObjectName("theta_min_R")
        self.gridLayout_3.addWidget(self.theta_min_R, 0, 3, 1, 1)
        self.theta_max_R = QtWidgets.QLineEdit(self.tab_4)
        self.theta_max_R.setMaximumSize(QtCore.QSize(200, 16777215))
        self.theta_max_R.setObjectName("theta_max_R")
        self.gridLayout_3.addWidget(self.theta_max_R, 0, 5, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_4)
        self.label_6.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 4, 1, 1)
        self.run_rotation_algorithm = QtWidgets.QPushButton(self.tab_4)
        self.run_rotation_algorithm.setObjectName("run_rotation_algorithm")
        self.gridLayout_3.addWidget(self.run_rotation_algorithm, 1, 3, 1, 3)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.ange_step_label_2 = QtWidgets.QLabel(self.tab_5)
        self.ange_step_label_2.setObjectName("ange_step_label_2")
        self.gridLayout_4.addWidget(self.ange_step_label_2, 0, 0, 2, 1)
        self.use_exact_grav_H = QtWidgets.QRadioButton(self.tab_5)
        self.use_exact_grav_H.setChecked(False)
        self.use_exact_grav_H.setObjectName("use_exact_grav_H")
        self.buttonGroup_3 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_3.setObjectName("buttonGroup_3")
        self.buttonGroup_3.addButton(self.use_exact_grav_H)
        self.gridLayout_4.addWidget(self.use_exact_grav_H, 2, 0, 1, 1)
        self.angle_bin_size_H = QtWidgets.QLineEdit(self.tab_5)
        self.angle_bin_size_H.setObjectName("angle_bin_size_H")
        self.gridLayout_4.addWidget(self.angle_bin_size_H, 0, 2, 2, 1, QtCore.Qt.AlignLeft)
        self.use_raw_idx_bin_H = QtWidgets.QRadioButton(self.tab_5)
        self.use_raw_idx_bin_H.setChecked(True)
        self.use_raw_idx_bin_H.setObjectName("use_raw_idx_bin_H")
        self.buttonGroup_9 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_9.setObjectName("buttonGroup_9")
        self.buttonGroup_9.addButton(self.use_raw_idx_bin_H)
        self.gridLayout_4.addWidget(self.use_raw_idx_bin_H, 3, 3, 1, 1)
        self.use_raw_idx_mask_H = QtWidgets.QRadioButton(self.tab_5)
        self.use_raw_idx_mask_H.setChecked(False)
        self.use_raw_idx_mask_H.setObjectName("use_raw_idx_mask_H")
        self.buttonGroup_9.addButton(self.use_raw_idx_mask_H)
        self.gridLayout_4.addWidget(self.use_raw_idx_mask_H, 2, 3, 1, 1)
        self.use_image_center_H = QtWidgets.QRadioButton(self.tab_5)
        self.use_image_center_H.setChecked(True)
        self.use_image_center_H.setObjectName("use_image_center_H")
        self.buttonGroup_3.addButton(self.use_image_center_H)
        self.gridLayout_4.addWidget(self.use_image_center_H, 3, 0, 2, 1)
        self.label_38 = QtWidgets.QLabel(self.tab_5)
        self.label_38.setObjectName("label_38")
        self.gridLayout_4.addWidget(self.label_38, 0, 3, 1, 1)
        self.integrate_interpol_H = QtWidgets.QRadioButton(self.tab_5)
        self.integrate_interpol_H.setEnabled(False)
        self.integrate_interpol_H.setObjectName("integrate_interpol_H")
        self.buttonGroup_9.addButton(self.integrate_interpol_H)
        self.gridLayout_4.addWidget(self.integrate_interpol_H, 4, 3, 1, 1)
        self.fit_cos_H = QtWidgets.QRadioButton(self.tab_5)
        self.fit_cos_H.setEnabled(False)
        self.fit_cos_H.setObjectName("fit_cos_H")
        self.gridLayout_4.addWidget(self.fit_cos_H, 1, 4, 2, 1)
        self.run_histogram_algorithm = QtWidgets.QPushButton(self.tab_5)
        self.run_histogram_algorithm.setObjectName("run_histogram_algorithm")
        self.gridLayout_4.addWidget(self.run_histogram_algorithm, 3, 4, 3, 1)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.run_mirror_algorithm = QtWidgets.QPushButton(self.tab_6)
        self.run_mirror_algorithm.setEnabled(False)
        self.run_mirror_algorithm.setMaximumSize(QtCore.QSize(500, 16777215))
        self.run_mirror_algorithm.setObjectName("run_mirror_algorithm")
        self.gridLayout_5.addWidget(self.run_mirror_algorithm, 2, 10, 2, 1)
        self.theta_max_M = QtWidgets.QLineEdit(self.tab_6)
        self.theta_max_M.setMaximumSize(QtCore.QSize(100, 16777215))
        self.theta_max_M.setObjectName("theta_max_M")
        self.gridLayout_5.addWidget(self.theta_max_M, 0, 7, 1, 1)
        self.left_vs_right_M = QtWidgets.QRadioButton(self.tab_6)
        self.left_vs_right_M.setChecked(True)
        self.left_vs_right_M.setObjectName("left_vs_right_M")
        self.buttonGroup_6 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_6.setObjectName("buttonGroup_6")
        self.buttonGroup_6.addButton(self.left_vs_right_M)
        self.gridLayout_5.addWidget(self.left_vs_right_M, 1, 9, 1, 1)
        self.theta_min_M = QtWidgets.QLineEdit(self.tab_6)
        self.theta_min_M.setMaximumSize(QtCore.QSize(100, 16777215))
        self.theta_min_M.setObjectName("theta_min_M")
        self.gridLayout_5.addWidget(self.theta_min_M, 0, 5, 1, 1)
        self.left_vs_right_up_vs_down_M = QtWidgets.QRadioButton(self.tab_6)
        self.left_vs_right_up_vs_down_M.setObjectName("left_vs_right_up_vs_down_M")
        self.buttonGroup_6.addButton(self.left_vs_right_up_vs_down_M)
        self.gridLayout_5.addWidget(self.left_vs_right_up_vs_down_M, 2, 9, 1, 1)
        self.mirror_vs_original_M = QtWidgets.QRadioButton(self.tab_6)
        self.mirror_vs_original_M.setObjectName("mirror_vs_original_M")
        self.buttonGroup_6.addButton(self.mirror_vs_original_M)
        self.gridLayout_5.addWidget(self.mirror_vs_original_M, 3, 9, 1, 1)
        self.use_image_center_M = QtWidgets.QRadioButton(self.tab_6)
        self.use_image_center_M.setObjectName("use_image_center_M")
        self.buttonGroup_5 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_5.setObjectName("buttonGroup_5")
        self.buttonGroup_5.addButton(self.use_image_center_M)
        self.gridLayout_5.addWidget(self.use_image_center_M, 1, 5, 2, 4)
        self.label_40 = QtWidgets.QLabel(self.tab_6)
        self.label_40.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_40.setObjectName("label_40")
        self.gridLayout_5.addWidget(self.label_40, 0, 4, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.tab_6)
        self.label_41.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_41.setObjectName("label_41")
        self.gridLayout_5.addWidget(self.label_41, 0, 6, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.tab_6)
        self.label_39.setObjectName("label_39")
        self.gridLayout_5.addWidget(self.label_39, 0, 9, 1, 1)
        self.use_exact_grav_M = QtWidgets.QRadioButton(self.tab_6)
        self.use_exact_grav_M.setChecked(True)
        self.use_exact_grav_M.setObjectName("use_exact_grav_M")
        self.buttonGroup_5.addButton(self.use_exact_grav_M)
        self.gridLayout_5.addWidget(self.use_exact_grav_M, 1, 4, 2, 1)
        self.tabWidget_2.addTab(self.tab_6, "")
        self.gridLayout_12.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_11.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.log_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.log_text.setMinimumSize(QtCore.QSize(0, 200))
        self.log_text.setMaximumSize(QtCore.QSize(16777215, 300))
        self.log_text.setObjectName("log_text")
        self.gridLayout_11.addWidget(self.log_text, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1363, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Polarization by Conical Refraction - UAB Quantum and Atom Optics Group"))
        self.label_19.setText(_translate("MainWindow", "Affine Transformation\n"
"Interpolation Algorithm:"))
        self.convert_selected_images.setText(_translate("MainWindow", "Convert Selected Images"))
        self.label_2.setText(_translate("MainWindow", "Image Directory:"))
        self.label_4.setText(_translate("MainWindow", "Choose Image Sizes for Computations:"))
        self.interpolation_alg_centering.setItemText(0, _translate("MainWindow", "bicubic interpolation"))
        self.interpolation_alg_centering.setItemText(1, _translate("MainWindow", "bilinear interpolation"))
        self.interpolation_alg_centering.setItemText(2, _translate("MainWindow", "nearest neighbor interpolation"))
        self.interpolation_alg_centering.setItemText(3, _translate("MainWindow", "Lanczos interpolation over 8x8 neighborhood"))
        self.interpolation_alg_centering.setItemText(4, _translate("MainWindow", "Bit exact bilinear interpolation"))
        self.interpolation_alg_centering.setItemText(5, _translate("MainWindow", "Bit exact nearest neighbor interpolation"))
        self.interpolation_alg_centering.setItemText(6, _translate("MainWindow", "resampling using pixel area relation"))
        self.use_i607.setText(_translate("MainWindow", "Use i607 images"))
        self.use_i203.setText(_translate("MainWindow", "Use i203 images"))
        self.change_image_directory.setText(_translate("MainWindow", "Change Directory"))
        self.label_3.setText(_translate("MainWindow", "Output Data Directory:"))
        self.change_output_directory.setText(_translate("MainWindow", "Change Directory"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Choose Output Directory and Images"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Settings for Input/Output"))
        self.label_7.setText(_translate("MainWindow", "b) Use all Converted Images in Output Data Directory:"))
        self.use_converted_i607.setText(_translate("MainWindow", " ./i607_converted_images"))
        self.show_plots.setText(_translate("MainWindow", "Show Plots"))
        self.output_plots.setText(_translate("MainWindow", "Output Plots"))
        self.use_current_images.setText(_translate("MainWindow", "a ) Use Selected Images \n"
"(if still not converted it will be done now)"))
        self.use_converted_i203.setText(_translate("MainWindow", " ./i203_converted_images"))
        self.groupBox.setTitle(_translate("MainWindow", "Search Algorithm for G (Max |Z| radius), R (Min difference angle), M (Min difference angle)"))
        self.label_14.setText(_translate("MainWindow", "Initial guess angle delta (Fibo. and Quad.):"))
        self.initial_guess_delta_rad.setText(_translate("MainWindow", "0.1"))
        self.label_18.setText(_translate("MainWindow", "Affine Transformation Interpolation Algorithm \n"
"(for algorithms R, M):"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Parameters for Brute Force Search"))
        self.ange_step_label.setText(_translate("MainWindow", "Step 1:"))
        self.zoom1_ratio.setText(_translate("MainWindow", "0.4"))
        self.label_11.setText(_translate("MainWindow", "Zoom 2 Ratio (<=1):"))
        self.label_9.setText(_translate("MainWindow", "Step 3\n"
"Precision:"))
        self.angle_step_1_pix.setText(_translate("MainWindow", "10"))
        self.zoom2_ratio.setText(_translate("MainWindow", "0.2"))
        self.label_8.setText(_translate("MainWindow", "Step 2:"))
        self.angle_step_1_rad.setText(_translate("MainWindow", "0.3"))
        self.label_10.setText(_translate("MainWindow", "Zoom 1 Ratio (<=1):"))
        self.label_42.setText(_translate("MainWindow", "R, M Angle\n"
"(rad)"))
        self.angle_step_2_pix.setText(_translate("MainWindow", "4"))
        self.angle_step_3_rad.setText(_translate("MainWindow", "0.005"))
        self.label_46.setText(_translate("MainWindow", "G Radius\n"
"(pixels)"))
        self.angle_step_3_pix.setText(_translate("MainWindow", "2"))
        self.angle_step_2_rad.setText(_translate("MainWindow", "0.07"))
        self.label_54.setText(_translate("MainWindow", "Parameters:"))
        self.brute.setText(_translate("MainWindow", "Brute Force Grid Search"))
        self.interpolation_alg_opt.setItemText(0, _translate("MainWindow", "bicubic interpolation"))
        self.interpolation_alg_opt.setItemText(1, _translate("MainWindow", "bilinear interpolation"))
        self.interpolation_alg_opt.setItemText(2, _translate("MainWindow", "nearest neighbor interpolation"))
        self.interpolation_alg_opt.setItemText(3, _translate("MainWindow", "Lanczos interpolation over 8x8 neighborhood"))
        self.interpolation_alg_opt.setItemText(4, _translate("MainWindow", "Bit exact bilinear interpolation"))
        self.interpolation_alg_opt.setItemText(5, _translate("MainWindow", "Bit exact nearest neighbor interpolation"))
        self.interpolation_alg_opt.setItemText(6, _translate("MainWindow", "resampling using pixel area relation"))
        self.initial_guess_delta_pix.setText(_translate("MainWindow", "0.1"))
        self.label.setText(_translate("MainWindow", "Select the Search Algorithm"))
        self.quadratic.setText(_translate("MainWindow", "Quadratic Fit 3 point search"))
        self.label_59.setText(_translate("MainWindow", "R, M Angle (rad)"))
        self.label_60.setText(_translate("MainWindow", "G Radius (pixels)"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Parameters for Quadratic Search"))
        self.label_62.setText(_translate("MainWindow", "Parameters for:"))
        self.label_55.setText(_translate("MainWindow", "G Radius (pixels)"))
        self.label_56.setText(_translate("MainWindow", "R,M Angle (rad)"))
        self.label_15.setText(_translate("MainWindow", "Precision* (rad):"))
        self.precision_quad_pix.setText(_translate("MainWindow", "0.01"))
        self.precision_quad_rad.setText(_translate("MainWindow", "0.01"))
        self.label_16.setText(_translate("MainWindow", "Maximum Iterations:"))
        self.max_it_quad.setText(_translate("MainWindow", "10000"))
        self.label_21.setText(_translate("MainWindow", "Cost tolerance (relative):"))
        self.cost_tolerance_quad.setText(_translate("MainWindow", "0.0001"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Parameters for Fibonacci Search"))
        self.label_63.setText(_translate("MainWindow", "Parameters for:"))
        self.label_57.setText(_translate("MainWindow", "G Radius (pixels)"))
        self.label_58.setText(_translate("MainWindow", "R,M Angle (rad)"))
        self.label_12.setText(_translate("MainWindow", "Precision* (rad):"))
        self.precision_fib_pix.setText(_translate("MainWindow", "0.01"))
        self.precision_fib_rad.setText(_translate("MainWindow", "0.01"))
        self.label_17.setText(_translate("MainWindow", "Maximum Points:"))
        self.max_points_fib.setText(_translate("MainWindow", "10000"))
        self.label_20.setText(_translate("MainWindow", "Cost tolerance (relative):"))
        self.cost_tolerance_fib.setText(_translate("MainWindow", "0"))
        self.fibonacci.setText(_translate("MainWindow", "Fibonacci 3 point search"))
        self.label_64.setText(_translate("MainWindow", "to"))
        self.max_rad_G.setText(_translate("MainWindow", "607"))
        self.min_rad_G.setText(_translate("MainWindow", "3"))
        self.label_65.setText(_translate("MainWindow", "Angle Range (pixels):"))
        self.use_exact_grav_G.setText(_translate("MainWindow", "Center exactly in Gravicenter"))
        self.use_image_center_G.setText(_translate("MainWindow", "Center in middle pixel of centered image"))
        self.run_gradient_algorithm.setText(_translate("MainWindow", "RUN G"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "G - Gradient Algorithm"))
        self.use_exact_grav_R.setText(_translate("MainWindow", "Use exact gravicenter"))
        self.use_image_center_R.setText(_translate("MainWindow", "Use centered image center"))
        self.label_5.setText(_translate("MainWindow", "Angle Range (rad):"))
        self.theta_min_R.setText(_translate("MainWindow", "-np.pi"))
        self.theta_max_R.setText(_translate("MainWindow", "np.pi"))
        self.label_6.setText(_translate("MainWindow", "to"))
        self.run_rotation_algorithm.setText(_translate("MainWindow", "RUN R"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "R - Rotatation Algorithm"))
        self.ange_step_label_2.setText(_translate("MainWindow", "Angle Bin size (rad) (Precision):"))
        self.use_exact_grav_H.setText(_translate("MainWindow", "Center exactly in Gravicenter"))
        self.angle_bin_size_H.setText(_translate("MainWindow", "0.1"))
        self.use_raw_idx_bin_H.setText(_translate("MainWindow", "Use Raw Indices Binning"))
        self.use_raw_idx_mask_H.setText(_translate("MainWindow", "Use Raw Indices Masker"))
        self.use_image_center_H.setText(_translate("MainWindow", "Center in middle pixel of \n"
"centered image"))
        self.label_38.setText(_translate("MainWindow", "Select which variant to use:"))
        self.integrate_interpol_H.setText(_translate("MainWindow", "Integrate Interpolation"))
        self.fit_cos_H.setText(_translate("MainWindow", "Refine minimum fitting to cos^2"))
        self.run_histogram_algorithm.setText(_translate("MainWindow", "RUN H"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "H - Radial Histogram Algorithm"))
        self.run_mirror_algorithm.setText(_translate("MainWindow", "RUN M"))
        self.theta_max_M.setText(_translate("MainWindow", "np.pi"))
        self.left_vs_right_M.setText(_translate("MainWindow", "Mirror Left vs Rigth Mode"))
        self.theta_min_M.setText(_translate("MainWindow", "-np.pi"))
        self.left_vs_right_up_vs_down_M.setText(_translate("MainWindow", "Mirror Left vs Rigth + Up vs Down Mode"))
        self.mirror_vs_original_M.setText(_translate("MainWindow", "Mirror vs Original Mode"))
        self.use_image_center_M.setText(_translate("MainWindow", "Use centered image center"))
        self.label_40.setText(_translate("MainWindow", "Angle Range (rad):"))
        self.label_41.setText(_translate("MainWindow", "to"))
        self.label_39.setText(_translate("MainWindow", "Select variant:"))
        self.use_exact_grav_M.setText(_translate("MainWindow", "Use exact gravicenter"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "M - Mirror Algorithm"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Measure Angle"))
        self.log_text.setPlainText(_translate("MainWindow", "> Choose images to work with\n"
"> Press Convert Selected Images to output them and leave them ready.\n"
"> Choose angle compuation algorithm and run it.\n"
"\n"
"Note that if \"Convert Selected Images\" is not clicked before running the algorithms, this will be done internally anyway.\n"
""))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

