# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './GUI/Design.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(866, 484)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_11.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.log_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log_text.sizePolicy().hasHeightForWidth())
        self.log_text.setSizePolicy(sizePolicy)
        self.log_text.setMinimumSize(QtCore.QSize(0, 0))
        self.log_text.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.log_text.setObjectName("log_text")
        self.gridLayout_11.addWidget(self.log_text, 2, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.change_image_directory = QtWidgets.QPushButton(self.tab)
        self.change_image_directory.setObjectName("change_image_directory")
        self.gridLayout.addWidget(self.change_image_directory, 1, 2, 1, 1)
        self.image_directory = QtWidgets.QLineEdit(self.tab)
        self.image_directory.setReadOnly(True)
        self.image_directory.setObjectName("image_directory")
        self.gridLayout.addWidget(self.image_directory, 1, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 2, 1, 1)
        self.change_output_directory = QtWidgets.QPushButton(self.tab)
        self.change_output_directory.setObjectName("change_output_directory")
        self.gridLayout.addWidget(self.change_output_directory, 3, 2, 1, 1)
        self.output_directory = QtWidgets.QLineEdit(self.tab)
        self.output_directory.setText("")
        self.output_directory.setReadOnly(True)
        self.output_directory.setObjectName("output_directory")
        self.gridLayout.addWidget(self.output_directory, 3, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 2, 1, 2)
        self.use_i607 = QtWidgets.QRadioButton(self.tab)
        self.use_i607.setChecked(True)
        self.use_i607.setObjectName("use_i607")
        self.gridLayout.addWidget(self.use_i607, 5, 2, 1, 1)
        self.convert_selected_images = QtWidgets.QPushButton(self.tab)
        self.convert_selected_images.setObjectName("convert_selected_images")
        self.gridLayout.addWidget(self.convert_selected_images, 5, 3, 1, 1)
        self.use_i203 = QtWidgets.QRadioButton(self.tab)
        self.use_i203.setObjectName("use_i203")
        self.gridLayout.addWidget(self.use_i203, 6, 2, 1, 1)
        self.interpolation_alg_centering = QtWidgets.QComboBox(self.tab)
        self.interpolation_alg_centering.setObjectName("interpolation_alg_centering")
        self.interpolation_alg_centering.addItem("")
        self.interpolation_alg_centering.addItem("")
        self.interpolation_alg_centering.addItem("")
        self.interpolation_alg_centering.addItem("")
        self.interpolation_alg_centering.addItem("")
        self.interpolation_alg_centering.addItem("")
        self.interpolation_alg_centering.addItem("")
        self.gridLayout.addWidget(self.interpolation_alg_centering, 7, 3, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 7, 2, 1, 1)
        self.picture_dir_tree = QtWidgets.QTreeWidget(self.tab)
        self.picture_dir_tree.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.picture_dir_tree.setIconSize(QtCore.QSize(35, 35))
        self.picture_dir_tree.setObjectName("picture_dir_tree")
        self.picture_dir_tree.headerItem().setText(0, "Choose one or multiple image files for calibration tests:")
        self.gridLayout.addWidget(self.picture_dir_tree, 0, 0, 8, 2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.output_plots = QtWidgets.QRadioButton(self.tab_2)
        self.output_plots.setChecked(True)
        self.output_plots.setAutoExclusive(False)
        self.output_plots.setObjectName("output_plots")
        self.gridLayout_6.addWidget(self.output_plots, 3, 1, 1, 1)
        self.show_plots = QtWidgets.QRadioButton(self.tab_2)
        self.show_plots.setEnabled(False)
        self.show_plots.setMaximumSize(QtCore.QSize(300, 16777215))
        self.show_plots.setAutoExclusive(False)
        self.show_plots.setObjectName("show_plots")
        self.gridLayout_6.addWidget(self.show_plots, 4, 1, 1, 1)
        self.use_current_images = QtWidgets.QRadioButton(self.tab_2)
        self.use_current_images.setChecked(False)
        self.use_current_images.setObjectName("use_current_images")
        self.gridLayout_6.addWidget(self.use_current_images, 3, 2, 1, 1)
        self.use_converted_i203 = QtWidgets.QRadioButton(self.tab_2)
        self.use_converted_i203.setObjectName("use_converted_i203")
        self.gridLayout_6.addWidget(self.use_converted_i203, 4, 3, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout_6.addWidget(self.label_23, 3, 0, 1, 1)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_2.sizePolicy().hasHeightForWidth())
        self.tabWidget_2.setSizePolicy(sizePolicy)
        self.tabWidget_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_64 = QtWidgets.QLabel(self.tab_3)
        self.label_64.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_64.setObjectName("label_64")
        self.gridLayout_2.addWidget(self.label_64, 0, 3, 1, 1)
        self.max_rad_G = QtWidgets.QLineEdit(self.tab_3)
        self.max_rad_G.setMaximumSize(QtCore.QSize(200, 16777215))
        self.max_rad_G.setObjectName("max_rad_G")
        self.gridLayout_2.addWidget(self.max_rad_G, 0, 4, 1, 1)
        self.min_rad_G = QtWidgets.QLineEdit(self.tab_3)
        self.min_rad_G.setMaximumSize(QtCore.QSize(200, 16777215))
        self.min_rad_G.setObjectName("min_rad_G")
        self.gridLayout_2.addWidget(self.min_rad_G, 0, 2, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.tab_3)
        self.label_65.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_65.setObjectName("label_65")
        self.gridLayout_2.addWidget(self.label_65, 0, 1, 1, 1)
        self.use_exact_grav_G = QtWidgets.QRadioButton(self.tab_3)
        self.use_exact_grav_G.setChecked(True)
        self.use_exact_grav_G.setObjectName("use_exact_grav_G")
        self.gridLayout_2.addWidget(self.use_exact_grav_G, 0, 0, 1, 1)
        self.use_image_center_G = QtWidgets.QRadioButton(self.tab_3)
        self.use_image_center_G.setObjectName("use_image_center_G")
        self.gridLayout_2.addWidget(self.use_image_center_G, 1, 0, 1, 1)
        self.run_gradient_algorithm = QtWidgets.QPushButton(self.tab_3)
        self.run_gradient_algorithm.setObjectName("run_gradient_algorithm")
        self.gridLayout_2.addWidget(self.run_gradient_algorithm, 1, 2, 1, 3)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.use_exact_grav_R = QtWidgets.QRadioButton(self.tab_4)
        self.use_exact_grav_R.setChecked(True)
        self.use_exact_grav_R.setObjectName("use_exact_grav_R")
        self.buttonGroup_4 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_4.setObjectName("buttonGroup_4")
        self.buttonGroup_4.addButton(self.use_exact_grav_R)
        self.gridLayout_3.addWidget(self.use_exact_grav_R, 0, 0, 1, 1)
        self.use_image_center_R = QtWidgets.QRadioButton(self.tab_4)
        self.use_image_center_R.setObjectName("use_image_center_R")
        self.buttonGroup_4.addButton(self.use_image_center_R)
        self.gridLayout_3.addWidget(self.use_image_center_R, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 2, 1, 1)
        self.theta_min_R = QtWidgets.QLineEdit(self.tab_4)
        self.theta_min_R.setMaximumSize(QtCore.QSize(200, 16777215))
        self.theta_min_R.setObjectName("theta_min_R")
        self.gridLayout_3.addWidget(self.theta_min_R, 0, 3, 1, 1)
        self.theta_max_R = QtWidgets.QLineEdit(self.tab_4)
        self.theta_max_R.setMaximumSize(QtCore.QSize(200, 16777215))
        self.theta_max_R.setObjectName("theta_max_R")
        self.gridLayout_3.addWidget(self.theta_max_R, 0, 5, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_4)
        self.label_6.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 4, 1, 1)
        self.run_rotation_algorithm = QtWidgets.QPushButton(self.tab_4)
        self.run_rotation_algorithm.setObjectName("run_rotation_algorithm")
        self.gridLayout_3.addWidget(self.run_rotation_algorithm, 1, 3, 1, 3)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.ange_step_label_2 = QtWidgets.QLabel(self.tab_5)
        self.ange_step_label_2.setObjectName("ange_step_label_2")
        self.gridLayout_4.addWidget(self.ange_step_label_2, 0, 0, 2, 1)
        self.use_exact_grav_H = QtWidgets.QRadioButton(self.tab_5)
        self.use_exact_grav_H.setChecked(False)
        self.use_exact_grav_H.setObjectName("use_exact_grav_H")
        self.buttonGroup_3 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_3.setObjectName("buttonGroup_3")
        self.buttonGroup_3.addButton(self.use_exact_grav_H)
        self.gridLayout_4.addWidget(self.use_exact_grav_H, 2, 0, 1, 1)
        self.angle_bin_size_H = QtWidgets.QLineEdit(self.tab_5)
        self.angle_bin_size_H.setObjectName("angle_bin_size_H")
        self.gridLayout_4.addWidget(self.angle_bin_size_H, 0, 2, 2, 1, QtCore.Qt.AlignLeft)
        self.use_raw_idx_bin_H = QtWidgets.QRadioButton(self.tab_5)
        self.use_raw_idx_bin_H.setChecked(True)
        self.use_raw_idx_bin_H.setObjectName("use_raw_idx_bin_H")
        self.buttonGroup_9 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_9.setObjectName("buttonGroup_9")
        self.buttonGroup_9.addButton(self.use_raw_idx_bin_H)
        self.gridLayout_4.addWidget(self.use_raw_idx_bin_H, 3, 3, 1, 1)
        self.use_raw_idx_mask_H = QtWidgets.QRadioButton(self.tab_5)
        self.use_raw_idx_mask_H.setChecked(False)
        self.use_raw_idx_mask_H.setObjectName("use_raw_idx_mask_H")
        self.buttonGroup_9.addButton(self.use_raw_idx_mask_H)
        self.gridLayout_4.addWidget(self.use_raw_idx_mask_H, 2, 3, 1, 1)
        self.use_image_center_H = QtWidgets.QRadioButton(self.tab_5)
        self.use_image_center_H.setChecked(True)
        self.use_image_center_H.setObjectName("use_image_center_H")
        self.buttonGroup_3.addButton(self.use_image_center_H)
        self.gridLayout_4.addWidget(self.use_image_center_H, 3, 0, 2, 1)
        self.label_38 = QtWidgets.QLabel(self.tab_5)
        self.label_38.setObjectName("label_38")
        self.gridLayout_4.addWidget(self.label_38, 0, 3, 1, 1)
        self.integrate_interpol_H = QtWidgets.QRadioButton(self.tab_5)
        self.integrate_interpol_H.setEnabled(False)
        self.integrate_interpol_H.setObjectName("integrate_interpol_H")
        self.buttonGroup_9.addButton(self.integrate_interpol_H)
        self.gridLayout_4.addWidget(self.integrate_interpol_H, 4, 3, 1, 1)
        self.fit_cos_H = QtWidgets.QRadioButton(self.tab_5)
        self.fit_cos_H.setEnabled(False)
        self.fit_cos_H.setObjectName("fit_cos_H")
        self.gridLayout_4.addWidget(self.fit_cos_H, 1, 4, 2, 1)
        self.run_histogram_algorithm = QtWidgets.QPushButton(self.tab_5)
        self.run_histogram_algorithm.setObjectName("run_histogram_algorithm")
        self.gridLayout_4.addWidget(self.run_histogram_algorithm, 3, 4, 3, 1)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_40 = QtWidgets.QLabel(self.tab_6)
        self.label_40.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_40.setObjectName("label_40")
        self.gridLayout_5.addWidget(self.label_40, 0, 0, 1, 1)
        self.theta_min_M = QtWidgets.QLineEdit(self.tab_6)
        self.theta_min_M.setEnabled(False)
        self.theta_min_M.setMaximumSize(QtCore.QSize(100, 16777215))
        self.theta_min_M.setObjectName("theta_min_M")
        self.gridLayout_5.addWidget(self.theta_min_M, 0, 1, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.tab_6)
        self.label_41.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_41.setObjectName("label_41")
        self.gridLayout_5.addWidget(self.label_41, 0, 2, 1, 1)
        self.theta_max_M = QtWidgets.QLineEdit(self.tab_6)
        self.theta_max_M.setEnabled(False)
        self.theta_max_M.setMaximumSize(QtCore.QSize(100, 16777215))
        self.theta_max_M.setObjectName("theta_max_M")
        self.gridLayout_5.addWidget(self.theta_max_M, 0, 3, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.tab_6)
        self.label_39.setObjectName("label_39")
        self.gridLayout_5.addWidget(self.label_39, 0, 4, 1, 1)
        self.use_masking_M = QtWidgets.QRadioButton(self.tab_6)
        self.use_masking_M.setChecked(True)
        self.use_masking_M.setObjectName("use_masking_M")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.use_masking_M)
        self.gridLayout_5.addWidget(self.use_masking_M, 1, 0, 1, 1)
        self.use_exact_grav_M = QtWidgets.QRadioButton(self.tab_6)
        self.use_exact_grav_M.setChecked(True)
        self.use_exact_grav_M.setObjectName("use_exact_grav_M")
        self.buttonGroup_5 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_5.setObjectName("buttonGroup_5")
        self.buttonGroup_5.addButton(self.use_exact_grav_M)
        self.gridLayout_5.addWidget(self.use_exact_grav_M, 1, 3, 1, 1)
        self.left_vs_right_M = QtWidgets.QRadioButton(self.tab_6)
        self.left_vs_right_M.setChecked(True)
        self.left_vs_right_M.setObjectName("left_vs_right_M")
        self.buttonGroup_6 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_6.setObjectName("buttonGroup_6")
        self.buttonGroup_6.addButton(self.left_vs_right_M)
        self.gridLayout_5.addWidget(self.left_vs_right_M, 1, 4, 1, 1)
        self.use_binning_M = QtWidgets.QRadioButton(self.tab_6)
        self.use_binning_M.setObjectName("use_binning_M")
        self.buttonGroup.addButton(self.use_binning_M)
        self.gridLayout_5.addWidget(self.use_binning_M, 2, 0, 1, 1)
        self.use_image_center_M = QtWidgets.QRadioButton(self.tab_6)
        self.use_image_center_M.setObjectName("use_image_center_M")
        self.buttonGroup_5.addButton(self.use_image_center_M)
        self.gridLayout_5.addWidget(self.use_image_center_M, 2, 3, 1, 1)
        self.up_vs_down_M = QtWidgets.QRadioButton(self.tab_6)
        self.up_vs_down_M.setObjectName("up_vs_down_M")
        self.buttonGroup_6.addButton(self.up_vs_down_M)
        self.gridLayout_5.addWidget(self.up_vs_down_M, 2, 4, 1, 1)
        self.use_affine_M = QtWidgets.QRadioButton(self.tab_6)
        self.use_affine_M.setObjectName("use_affine_M")
        self.buttonGroup.addButton(self.use_affine_M)
        self.gridLayout_5.addWidget(self.use_affine_M, 3, 0, 1, 1)
        self.run_mirror_algorithm = QtWidgets.QPushButton(self.tab_6)
        self.run_mirror_algorithm.setEnabled(True)
        self.run_mirror_algorithm.setMaximumSize(QtCore.QSize(500, 16777215))
        self.run_mirror_algorithm.setObjectName("run_mirror_algorithm")
        self.gridLayout_5.addWidget(self.run_mirror_algorithm, 4, 5, 1, 1)
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_10)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.tab_10)
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.tab_12)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_54 = QtWidgets.QLabel(self.tab_12)
        self.label_54.setObjectName("label_54")
        self.gridLayout_15.addWidget(self.label_54, 0, 0, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.tab_12)
        self.label_46.setObjectName("label_46")
        self.gridLayout_15.addWidget(self.label_46, 0, 1, 1, 3)
        self.label_42 = QtWidgets.QLabel(self.tab_12)
        self.label_42.setObjectName("label_42")
        self.gridLayout_15.addWidget(self.label_42, 0, 4, 1, 1)
        self.ange_step_label = QtWidgets.QLabel(self.tab_12)
        self.ange_step_label.setObjectName("ange_step_label")
        self.gridLayout_15.addWidget(self.ange_step_label, 1, 0, 1, 2)
        self.angle_step_1_pix = QtWidgets.QLineEdit(self.tab_12)
        self.angle_step_1_pix.setObjectName("angle_step_1_pix")
        self.gridLayout_15.addWidget(self.angle_step_1_pix, 1, 2, 1, 2)
        self.angle_step_1_rad = QtWidgets.QLineEdit(self.tab_12)
        self.angle_step_1_rad.setObjectName("angle_step_1_rad")
        self.gridLayout_15.addWidget(self.angle_step_1_rad, 1, 4, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_12)
        self.label_8.setObjectName("label_8")
        self.gridLayout_15.addWidget(self.label_8, 2, 0, 1, 2)
        self.angle_step_2_pix = QtWidgets.QLineEdit(self.tab_12)
        self.angle_step_2_pix.setObjectName("angle_step_2_pix")
        self.gridLayout_15.addWidget(self.angle_step_2_pix, 2, 2, 1, 2)
        self.angle_step_2_rad = QtWidgets.QLineEdit(self.tab_12)
        self.angle_step_2_rad.setObjectName("angle_step_2_rad")
        self.gridLayout_15.addWidget(self.angle_step_2_rad, 2, 4, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_12)
        self.label_9.setObjectName("label_9")
        self.gridLayout_15.addWidget(self.label_9, 3, 0, 1, 2)
        self.angle_step_3_pix = QtWidgets.QLineEdit(self.tab_12)
        self.angle_step_3_pix.setObjectName("angle_step_3_pix")
        self.gridLayout_15.addWidget(self.angle_step_3_pix, 3, 2, 1, 2)
        self.angle_step_3_rad = QtWidgets.QLineEdit(self.tab_12)
        self.angle_step_3_rad.setObjectName("angle_step_3_rad")
        self.gridLayout_15.addWidget(self.angle_step_3_rad, 3, 4, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_12)
        self.label_10.setObjectName("label_10")
        self.gridLayout_15.addWidget(self.label_10, 4, 0, 1, 3)
        self.zoom1_ratio = QtWidgets.QLineEdit(self.tab_12)
        self.zoom1_ratio.setObjectName("zoom1_ratio")
        self.gridLayout_15.addWidget(self.zoom1_ratio, 4, 3, 1, 2)
        self.label_11 = QtWidgets.QLabel(self.tab_12)
        self.label_11.setObjectName("label_11")
        self.gridLayout_15.addWidget(self.label_11, 5, 0, 1, 3)
        self.zoom2_ratio = QtWidgets.QLineEdit(self.tab_12)
        self.zoom2_ratio.setObjectName("zoom2_ratio")
        self.gridLayout_15.addWidget(self.zoom2_ratio, 5, 3, 1, 2)
        self.tabWidget_4.addTab(self.tab_12, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_13)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_62 = QtWidgets.QLabel(self.tab_13)
        self.label_62.setObjectName("label_62")
        self.gridLayout_8.addWidget(self.label_62, 0, 0, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.tab_13)
        self.label_55.setObjectName("label_55")
        self.gridLayout_8.addWidget(self.label_55, 0, 1, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.tab_13)
        self.label_56.setObjectName("label_56")
        self.gridLayout_8.addWidget(self.label_56, 0, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_13)
        self.label_15.setObjectName("label_15")
        self.gridLayout_8.addWidget(self.label_15, 1, 0, 1, 1)
        self.precision_quad_pix = QtWidgets.QLineEdit(self.tab_13)
        self.precision_quad_pix.setObjectName("precision_quad_pix")
        self.gridLayout_8.addWidget(self.precision_quad_pix, 1, 1, 1, 1)
        self.precision_quad_rad = QtWidgets.QLineEdit(self.tab_13)
        self.precision_quad_rad.setObjectName("precision_quad_rad")
        self.gridLayout_8.addWidget(self.precision_quad_rad, 1, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tab_13)
        self.label_16.setObjectName("label_16")
        self.gridLayout_8.addWidget(self.label_16, 2, 0, 1, 1)
        self.max_it_quad = QtWidgets.QLineEdit(self.tab_13)
        self.max_it_quad.setObjectName("max_it_quad")
        self.gridLayout_8.addWidget(self.max_it_quad, 2, 1, 1, 2)
        self.label_21 = QtWidgets.QLabel(self.tab_13)
        self.label_21.setObjectName("label_21")
        self.gridLayout_8.addWidget(self.label_21, 3, 0, 1, 1)
        self.cost_tolerance_quad = QtWidgets.QLineEdit(self.tab_13)
        self.cost_tolerance_quad.setObjectName("cost_tolerance_quad")
        self.gridLayout_8.addWidget(self.cost_tolerance_quad, 3, 1, 1, 2)
        self.tabWidget_4.addTab(self.tab_13, "")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.tab_14)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_63 = QtWidgets.QLabel(self.tab_14)
        self.label_63.setObjectName("label_63")
        self.gridLayout_16.addWidget(self.label_63, 0, 0, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.tab_14)
        self.label_57.setObjectName("label_57")
        self.gridLayout_16.addWidget(self.label_57, 0, 1, 1, 2)
        self.label_58 = QtWidgets.QLabel(self.tab_14)
        self.label_58.setObjectName("label_58")
        self.gridLayout_16.addWidget(self.label_58, 0, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab_14)
        self.label_12.setObjectName("label_12")
        self.gridLayout_16.addWidget(self.label_12, 1, 0, 1, 1)
        self.precision_fib_pix = QtWidgets.QLineEdit(self.tab_14)
        self.precision_fib_pix.setObjectName("precision_fib_pix")
        self.gridLayout_16.addWidget(self.precision_fib_pix, 1, 1, 1, 2)
        self.precision_fib_rad = QtWidgets.QLineEdit(self.tab_14)
        self.precision_fib_rad.setObjectName("precision_fib_rad")
        self.gridLayout_16.addWidget(self.precision_fib_rad, 1, 3, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab_14)
        self.label_17.setObjectName("label_17")
        self.gridLayout_16.addWidget(self.label_17, 2, 0, 1, 2)
        self.max_points_fib = QtWidgets.QLineEdit(self.tab_14)
        self.max_points_fib.setObjectName("max_points_fib")
        self.gridLayout_16.addWidget(self.max_points_fib, 2, 2, 1, 2)
        self.label_20 = QtWidgets.QLabel(self.tab_14)
        self.label_20.setObjectName("label_20")
        self.gridLayout_16.addWidget(self.label_20, 3, 0, 1, 2)
        self.cost_tolerance_fib = QtWidgets.QLineEdit(self.tab_14)
        self.cost_tolerance_fib.setObjectName("cost_tolerance_fib")
        self.gridLayout_16.addWidget(self.cost_tolerance_fib, 3, 2, 1, 2)
        self.tabWidget_4.addTab(self.tab_14, "")
        self.gridLayout_7.addWidget(self.tabWidget_4, 0, 2, 9, 1)
        self.initial_guess_delta_pix = QtWidgets.QLineEdit(self.tab_10)
        self.initial_guess_delta_pix.setMaximumSize(QtCore.QSize(100, 16777215))
        self.initial_guess_delta_pix.setObjectName("initial_guess_delta_pix")
        self.gridLayout_7.addWidget(self.initial_guess_delta_pix, 2, 0, 1, 1)
        self.initial_guess_delta_rad = QtWidgets.QLineEdit(self.tab_10)
        self.initial_guess_delta_rad.setMaximumSize(QtCore.QSize(100, 16777215))
        self.initial_guess_delta_rad.setObjectName("initial_guess_delta_rad")
        self.gridLayout_7.addWidget(self.initial_guess_delta_rad, 2, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab_10)
        self.label_18.setObjectName("label_18")
        self.gridLayout_7.addWidget(self.label_18, 3, 0, 1, 2)
        self.interpolation_alg_opt = QtWidgets.QComboBox(self.tab_10)
        self.interpolation_alg_opt.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.interpolation_alg_opt.setObjectName("interpolation_alg_opt")
        self.interpolation_alg_opt.addItem("")
        self.interpolation_alg_opt.addItem("")
        self.interpolation_alg_opt.addItem("")
        self.interpolation_alg_opt.addItem("")
        self.interpolation_alg_opt.addItem("")
        self.interpolation_alg_opt.addItem("")
        self.interpolation_alg_opt.addItem("")
        self.gridLayout_7.addWidget(self.interpolation_alg_opt, 4, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.tab_10)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 5, 0, 1, 1)
        self.brute = QtWidgets.QRadioButton(self.tab_10)
        self.brute.setObjectName("brute")
        self.gridLayout_7.addWidget(self.brute, 6, 0, 1, 1)
        self.fibonacci = QtWidgets.QRadioButton(self.tab_10)
        self.fibonacci.setChecked(False)
        self.fibonacci.setObjectName("fibonacci")
        self.gridLayout_7.addWidget(self.fibonacci, 7, 0, 1, 1)
        self.quadratic = QtWidgets.QRadioButton(self.tab_10)
        self.quadratic.setChecked(True)
        self.quadratic.setObjectName("quadratic")
        self.gridLayout_7.addWidget(self.quadratic, 8, 0, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.tab_10)
        self.label_60.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_60.setObjectName("label_60")
        self.gridLayout_7.addWidget(self.label_60, 0, 0, 2, 1)
        self.label_59 = QtWidgets.QLabel(self.tab_10)
        self.label_59.setObjectName("label_59")
        self.gridLayout_7.addWidget(self.label_59, 0, 1, 2, 1)
        self.tabWidget_2.addTab(self.tab_10, "")
        self.gridLayout_6.addWidget(self.tabWidget_2, 0, 0, 2, 5)
        self.use_converted_i607 = QtWidgets.QRadioButton(self.tab_2)
        self.use_converted_i607.setChecked(True)
        self.use_converted_i607.setObjectName("use_converted_i607")
        self.gridLayout_6.addWidget(self.use_converted_i607, 3, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 4, 2, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.tab_7)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.liveR = QtWidgets.QCheckBox(self.tab_7)
        self.liveR.setObjectName("liveR")
        self.buttonGroup_7 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_7.setObjectName("buttonGroup_7")
        self.buttonGroup_7.addButton(self.liveR)
        self.gridLayout_14.addWidget(self.liveR, 4, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_14.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tab_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout_14.addWidget(self.label_22, 0, 1, 1, 2)
        self.testCamera = QtWidgets.QPushButton(self.tab_7)
        self.testCamera.setObjectName("testCamera")
        self.gridLayout_14.addWidget(self.testCamera, 5, 0, 1, 1)
        self.liveG = QtWidgets.QCheckBox(self.tab_7)
        self.liveG.setChecked(True)
        self.liveG.setObjectName("liveG")
        self.buttonGroup_7.addButton(self.liveG)
        self.gridLayout_14.addWidget(self.liveG, 2, 1, 1, 1)
        self.grabReference = QtWidgets.QPushButton(self.tab_7)
        self.grabReference.setObjectName("grabReference")
        self.gridLayout_14.addWidget(self.grabReference, 5, 1, 1, 1)
        self.use_BaslerCamera = QtWidgets.QRadioButton(self.tab_7)
        self.use_BaslerCamera.setObjectName("use_BaslerCamera")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.use_BaslerCamera)
        self.gridLayout_14.addWidget(self.use_BaslerCamera, 4, 0, 1, 1)
        self.liveM = QtWidgets.QCheckBox(self.tab_7)
        self.liveM.setObjectName("liveM")
        self.buttonGroup_7.addButton(self.liveM)
        self.gridLayout_14.addWidget(self.liveM, 4, 2, 1, 1)
        self.use_PiCamera = QtWidgets.QRadioButton(self.tab_7)
        self.use_PiCamera.setChecked(True)
        self.use_PiCamera.setObjectName("use_PiCamera")
        self.buttonGroup_2.addButton(self.use_PiCamera)
        self.gridLayout_14.addWidget(self.use_PiCamera, 2, 0, 1, 1)
        self.runCamera = QtWidgets.QPushButton(self.tab_7)
        self.runCamera.setEnabled(False)
        self.runCamera.setObjectName("runCamera")
        self.gridLayout_14.addWidget(self.runCamera, 5, 2, 1, 1)
        self.liveH = QtWidgets.QCheckBox(self.tab_7)
        self.liveH.setObjectName("liveH")
        self.buttonGroup_7.addButton(self.liveH)
        self.gridLayout_14.addWidget(self.liveH, 2, 2, 1, 1)
        self.stopCamera = QtWidgets.QPushButton(self.tab_7)
        self.stopCamera.setEnabled(False)
        self.stopCamera.setObjectName("stopCamera")
        self.gridLayout_14.addWidget(self.stopCamera, 5, 3, 1, 1)
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_7)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_8)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_26 = QtWidgets.QLabel(self.tab_8)
        self.label_26.setObjectName("label_26")
        self.gridLayout_9.addWidget(self.label_26, 0, 0, 1, 2)
        self.pi_w = QtWidgets.QLineEdit(self.tab_8)
        self.pi_w.setObjectName("pi_w")
        self.gridLayout_9.addWidget(self.pi_w, 0, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.tab_8)
        self.label_27.setObjectName("label_27")
        self.gridLayout_9.addWidget(self.label_27, 0, 3, 1, 1)
        self.pi_h = QtWidgets.QLineEdit(self.tab_8)
        self.pi_h.setObjectName("pi_h")
        self.gridLayout_9.addWidget(self.pi_h, 0, 4, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.tab_8)
        self.label_31.setObjectName("label_31")
        self.gridLayout_9.addWidget(self.label_31, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_9.addWidget(self.lineEdit_2, 1, 1, 1, 2)
        self.radioButton = QtWidgets.QRadioButton(self.tab_8)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.buttonGroup_13 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_13.setObjectName("buttonGroup_13")
        self.buttonGroup_13.addButton(self.radioButton)
        self.gridLayout_9.addWidget(self.radioButton, 1, 3, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.tab_8)
        self.radioButton_2.setEnabled(False)
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup_13.addButton(self.radioButton_2)
        self.gridLayout_9.addWidget(self.radioButton_2, 1, 4, 1, 1)
        self.tabWidget_3.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.tabWidget_3.addTab(self.tab_9, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_11)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.showContinously = QtWidgets.QRadioButton(self.tab_11)
        self.showContinously.setChecked(False)
        self.showContinously.setObjectName("showContinously")
        self.gridLayout_10.addWidget(self.showContinously, 0, 2, 1, 1)
        self.progressBar_Life = QtWidgets.QProgressBar(self.tab_11)
        self.progressBar_Life.setProperty("value", 0)
        self.progressBar_Life.setObjectName("progressBar_Life")
        self.gridLayout_10.addWidget(self.progressBar_Life, 8, 2, 1, 3)
        self.referenceAngle = QtWidgets.QLineEdit(self.tab_11)
        self.referenceAngle.setObjectName("referenceAngle")
        self.gridLayout_10.addWidget(self.referenceAngle, 0, 1, 1, 1)
        self.outputEvery = QtWidgets.QLineEdit(self.tab_11)
        self.outputEvery.setObjectName("outputEvery")
        self.gridLayout_10.addWidget(self.outputEvery, 8, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.tab_11)
        self.label_25.setObjectName("label_25")
        self.gridLayout_10.addWidget(self.label_25, 8, 0, 1, 1)
        self.saveLifeOutput = QtWidgets.QRadioButton(self.tab_11)
        self.saveLifeOutput.setChecked(False)
        self.saveLifeOutput.setObjectName("saveLifeOutput")
        self.gridLayout_10.addWidget(self.saveLifeOutput, 4, 0, 1, 1)
        self.dont_SaveLifeOutput = QtWidgets.QRadioButton(self.tab_11)
        self.dont_SaveLifeOutput.setObjectName("dont_SaveLifeOutput")
        self.gridLayout_10.addWidget(self.dont_SaveLifeOutput, 4, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.tab_11)
        self.label_30.setObjectName("label_30")
        self.gridLayout_10.addWidget(self.label_30, 4, 2, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.tab_11)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_10.addWidget(self.lineEdit, 4, 3, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.tab_11)
        self.label_29.setObjectName("label_29")
        self.gridLayout_10.addWidget(self.label_29, 0, 0, 1, 1)
        self.showOnlyOutputted = QtWidgets.QRadioButton(self.tab_11)
        self.showOnlyOutputted.setEnabled(False)
        self.showOnlyOutputted.setObjectName("showOnlyOutputted")
        self.gridLayout_10.addWidget(self.showOnlyOutputted, 1, 2, 1, 1)
        self.showNothing = QtWidgets.QRadioButton(self.tab_11)
        self.showNothing.setObjectName("showNothing")
        self.gridLayout_10.addWidget(self.showNothing, 2, 2, 1, 1)
        self.showImagesAngles = QtWidgets.QRadioButton(self.tab_11)
        self.showImagesAngles.setChecked(True)
        self.showImagesAngles.setObjectName("showImagesAngles")
        self.gridLayout_10.addWidget(self.showImagesAngles, 1, 3, 1, 1)
        self.showAll = QtWidgets.QRadioButton(self.tab_11)
        self.showAll.setEnabled(False)
        self.showAll.setObjectName("showAll")
        self.gridLayout_10.addWidget(self.showAll, 2, 3, 1, 1)
        self.imagesInChunks = QtWidgets.QLineEdit(self.tab_11)
        self.imagesInChunks.setObjectName("imagesInChunks")
        self.gridLayout_10.addWidget(self.imagesInChunks, 1, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.tab_11)
        self.label_28.setObjectName("label_28")
        self.gridLayout_10.addWidget(self.label_28, 1, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.tab_11)
        self.label_24.setObjectName("label_24")
        self.gridLayout_10.addWidget(self.label_24, 2, 0, 1, 1)
        self.totalFrames = QtWidgets.QLineEdit(self.tab_11)
        self.totalFrames.setObjectName("totalFrames")
        self.gridLayout_10.addWidget(self.totalFrames, 2, 1, 1, 1)
        self.tabWidget_3.addTab(self.tab_11, "")
        self.gridLayout_14.addWidget(self.tabWidget_3, 14, 0, 1, 4)
        self.tabWidget.addTab(self.tab_7, "")
        self.gridLayout_11.addWidget(self.tabWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.tabWidget_2.setCurrentIndex(4)
        self.tabWidget_4.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Polarization by Conical Refraction - UAB Quantum and Atom Optics Group"))
        self.log_text.setPlainText(_translate("MainWindow", "> Choose images to work with\n"
"> Press Convert Selected Images to output them and leave them ready.\n"
"> Choose angle compuation algorithm and run it.\n"
"\n"
"Note that if \"Convert Selected Images\" is not clicked before running the algorithms, this will be done internally anyway.\n"
""))
        self.label_2.setText(_translate("MainWindow", "Image Directory:"))
        self.change_image_directory.setText(_translate("MainWindow", "Change Directory"))
        self.label_3.setText(_translate("MainWindow", "Output Data Directory:"))
        self.change_output_directory.setText(_translate("MainWindow", "Change Directory"))
        self.label_4.setText(_translate("MainWindow", "Choose Image Sizes for Computations:"))
        self.use_i607.setText(_translate("MainWindow", "Use i607 images"))
        self.convert_selected_images.setText(_translate("MainWindow", "Convert Selected Images"))
        self.use_i203.setText(_translate("MainWindow", "Use i203 images"))
        self.interpolation_alg_centering.setItemText(0, _translate("MainWindow", "bicubic interpolation"))
        self.interpolation_alg_centering.setItemText(1, _translate("MainWindow", "bilinear interpolation"))
        self.interpolation_alg_centering.setItemText(2, _translate("MainWindow", "nearest neighbor interpolation"))
        self.interpolation_alg_centering.setItemText(3, _translate("MainWindow", "Lanczos interpolation over 8x8 neighborhood"))
        self.interpolation_alg_centering.setItemText(4, _translate("MainWindow", "Bit exact bilinear interpolation"))
        self.interpolation_alg_centering.setItemText(5, _translate("MainWindow", "Bit exact nearest neighbor interpolation"))
        self.interpolation_alg_centering.setItemText(6, _translate("MainWindow", "resampling using pixel area relation"))
        self.label_19.setText(_translate("MainWindow", "Affine Transformation\n"
"Interpolation Algorithm:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Choose Output Directory and Input Test Images"))
        self.output_plots.setText(_translate("MainWindow", "Output Plots"))
        self.show_plots.setText(_translate("MainWindow", "Show Plots"))
        self.use_current_images.setText(_translate("MainWindow", "a ) Use Selected Images \n"
"(if still not converted it will be done now)"))
        self.use_converted_i203.setText(_translate("MainWindow", " ./i203_converted_images"))
        self.label_23.setText(_translate("MainWindow", "Settings for Sanity Check Input/Output"))
        self.label_64.setText(_translate("MainWindow", "to"))
        self.max_rad_G.setText(_translate("MainWindow", "607"))
        self.min_rad_G.setText(_translate("MainWindow", "3"))
        self.label_65.setText(_translate("MainWindow", "Angle Range (pixels):"))
        self.use_exact_grav_G.setText(_translate("MainWindow", "Center exactly in Gravicenter"))
        self.use_image_center_G.setText(_translate("MainWindow", "Center in middle pixel of centered image"))
        self.run_gradient_algorithm.setText(_translate("MainWindow", "RUN G"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "G - Gradient Algorithm"))
        self.use_exact_grav_R.setText(_translate("MainWindow", "Use exact gravicenter"))
        self.use_image_center_R.setText(_translate("MainWindow", "Use centered image center"))
        self.label_5.setText(_translate("MainWindow", "Angle Range (rad):"))
        self.theta_min_R.setText(_translate("MainWindow", "-np.pi"))
        self.theta_max_R.setText(_translate("MainWindow", "np.pi"))
        self.label_6.setText(_translate("MainWindow", "to"))
        self.run_rotation_algorithm.setText(_translate("MainWindow", "RUN R"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "R - Rotatation Algorithm"))
        self.ange_step_label_2.setText(_translate("MainWindow", "Angle Bin size (rad) (Precision):"))
        self.use_exact_grav_H.setText(_translate("MainWindow", "Center exactly in Gravicenter"))
        self.angle_bin_size_H.setText(_translate("MainWindow", "0.1"))
        self.use_raw_idx_bin_H.setText(_translate("MainWindow", "Use Raw Indices Binning"))
        self.use_raw_idx_mask_H.setText(_translate("MainWindow", "Use Raw Indices Masker"))
        self.use_image_center_H.setText(_translate("MainWindow", "Center in middle pixel of \n"
"centered image"))
        self.label_38.setText(_translate("MainWindow", "Select which variant to use:"))
        self.integrate_interpol_H.setText(_translate("MainWindow", "Integrate Interpolation"))
        self.fit_cos_H.setText(_translate("MainWindow", "Refine minimum fitting to cos^2"))
        self.run_histogram_algorithm.setText(_translate("MainWindow", "RUN H"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "H - Radial Histogram Algorithm"))
        self.label_40.setText(_translate("MainWindow", "Angle Range (rad):"))
        self.theta_min_M.setText(_translate("MainWindow", "0"))
        self.label_41.setText(_translate("MainWindow", "to"))
        self.theta_max_M.setText(_translate("MainWindow", "np.pi"))
        self.label_39.setText(_translate("MainWindow", "Select variant:"))
        self.use_masking_M.setText(_translate("MainWindow", "Use Masking"))
        self.use_exact_grav_M.setText(_translate("MainWindow", "Use exact gravicenter"))
        self.left_vs_right_M.setText(_translate("MainWindow", "Mirror Left vs Rigth Mode (min dif)"))
        self.use_binning_M.setText(_translate("MainWindow", "Use binning"))
        self.use_image_center_M.setText(_translate("MainWindow", "Use centered image center"))
        self.up_vs_down_M.setText(_translate("MainWindow", "Mirror Up vs Down Mode (max dif)"))
        self.use_affine_M.setText(_translate("MainWindow", "Use Affine Mirrorring with interpolation"))
        self.run_mirror_algorithm.setText(_translate("MainWindow", "RUN M"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "M - Mirror Algorithm"))
        self.label_54.setText(_translate("MainWindow", "Parameters:"))
        self.label_46.setText(_translate("MainWindow", "G Radius (pixels)"))
        self.label_42.setText(_translate("MainWindow", "R, M Angle (rad)"))
        self.ange_step_label.setText(_translate("MainWindow", "Step 1:"))
        self.angle_step_1_pix.setText(_translate("MainWindow", "10"))
        self.angle_step_1_rad.setText(_translate("MainWindow", "0.3"))
        self.label_8.setText(_translate("MainWindow", "Step 2:"))
        self.angle_step_2_pix.setText(_translate("MainWindow", "4"))
        self.angle_step_2_rad.setText(_translate("MainWindow", "0.07"))
        self.label_9.setText(_translate("MainWindow", "Step 3\n"
"Precision:"))
        self.angle_step_3_pix.setText(_translate("MainWindow", "2"))
        self.angle_step_3_rad.setText(_translate("MainWindow", "0.005"))
        self.label_10.setText(_translate("MainWindow", "Zoom 1 Ratio (<=1):"))
        self.zoom1_ratio.setText(_translate("MainWindow", "0.4"))
        self.label_11.setText(_translate("MainWindow", "Zoom 2 Ratio (<=1):"))
        self.zoom2_ratio.setText(_translate("MainWindow", "0.2"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_12), _translate("MainWindow", "Parameters for Brute Force Search"))
        self.label_62.setText(_translate("MainWindow", "Parameters for:"))
        self.label_55.setText(_translate("MainWindow", "G Radius (pixels)"))
        self.label_56.setText(_translate("MainWindow", "R,M Angle (rad)"))
        self.label_15.setText(_translate("MainWindow", "Precision* (rad):"))
        self.precision_quad_pix.setText(_translate("MainWindow", "0.01"))
        self.precision_quad_rad.setText(_translate("MainWindow", "0.01"))
        self.label_16.setText(_translate("MainWindow", "Maximum Iterations:"))
        self.max_it_quad.setText(_translate("MainWindow", "10000"))
        self.label_21.setText(_translate("MainWindow", "Cost tolerance (relative):"))
        self.cost_tolerance_quad.setText(_translate("MainWindow", "0.0001"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_13), _translate("MainWindow", "Parameters for Quadratic Search"))
        self.label_63.setText(_translate("MainWindow", "Parameters for:"))
        self.label_57.setText(_translate("MainWindow", "G Radius (pixels)"))
        self.label_58.setText(_translate("MainWindow", "R,M Angle (rad)"))
        self.label_12.setText(_translate("MainWindow", "Precision* (rad):"))
        self.precision_fib_pix.setText(_translate("MainWindow", "0.01"))
        self.precision_fib_rad.setText(_translate("MainWindow", "0.01"))
        self.label_17.setText(_translate("MainWindow", "Maximum Points:"))
        self.max_points_fib.setText(_translate("MainWindow", "10000"))
        self.label_20.setText(_translate("MainWindow", "Cost tolerance (relative):"))
        self.cost_tolerance_fib.setText(_translate("MainWindow", "0"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_14), _translate("MainWindow", "Parameters for Fibonacci Search"))
        self.initial_guess_delta_pix.setText(_translate("MainWindow", "0.1"))
        self.initial_guess_delta_rad.setText(_translate("MainWindow", "0.1"))
        self.label_18.setText(_translate("MainWindow", "Affine Transformation Interpolation Algorithm (for algorithms R, M):"))
        self.interpolation_alg_opt.setItemText(0, _translate("MainWindow", "bicubic interpolation"))
        self.interpolation_alg_opt.setItemText(1, _translate("MainWindow", "bilinear interpolation"))
        self.interpolation_alg_opt.setItemText(2, _translate("MainWindow", "nearest neighbor interpolation"))
        self.interpolation_alg_opt.setItemText(3, _translate("MainWindow", "Lanczos interpolation over 8x8 neighborhood"))
        self.interpolation_alg_opt.setItemText(4, _translate("MainWindow", "Bit exact bilinear interpolation"))
        self.interpolation_alg_opt.setItemText(5, _translate("MainWindow", "Bit exact nearest neighbor interpolation"))
        self.interpolation_alg_opt.setItemText(6, _translate("MainWindow", "resampling using pixel area relation"))
        self.label.setText(_translate("MainWindow", "Select the Search Algorithm"))
        self.brute.setText(_translate("MainWindow", "Brute Force Grid Search"))
        self.fibonacci.setText(_translate("MainWindow", "Fibonacci 3 point search"))
        self.quadratic.setText(_translate("MainWindow", "Quadratic Fit 3 point search"))
        self.label_60.setText(_translate("MainWindow", "Initial guess delta (Fib. and Quad.):\n"
" G Radius (pixels):"))
        self.label_59.setText(_translate("MainWindow", "Guess delta\n"
"R, M Angle (rad):"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_10), _translate("MainWindow", "Search Algorithm for G, R and M"))
        self.use_converted_i607.setText(_translate("MainWindow", " ./i607_converted_images"))
        self.label_7.setText(_translate("MainWindow", "b) Use all Converted Images in Output Data Directory:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Algorithm Settings and Test"))
        self.liveR.setText(_translate("MainWindow", "R - Rotation"))
        self.label_13.setText(_translate("MainWindow", "Choose Camera to Use"))
        self.label_22.setText(_translate("MainWindow", "Choose Algorithm"))
        self.testCamera.setText(_translate("MainWindow", "TEST Camera"))
        self.liveG.setText(_translate("MainWindow", "G - Gradient"))
        self.grabReference.setText(_translate("MainWindow", "GRAB REFERENCE CHUNK"))
        self.use_BaslerCamera.setText(_translate("MainWindow", "Basler Camera"))
        self.liveM.setText(_translate("MainWindow", "M - Mirror"))
        self.use_PiCamera.setText(_translate("MainWindow", "HQ PiCamera"))
        self.runCamera.setText(_translate("MainWindow", "RUN Camera"))
        self.liveH.setText(_translate("MainWindow", "H - Radial Histogram"))
        self.stopCamera.setText(_translate("MainWindow", "STOP Camera"))
        self.label_26.setText(_translate("MainWindow", "Resolution (wxh):\n"
"Max (4056 x 3040)"))
        self.pi_w.setText(_translate("MainWindow", "2592"))
        self.label_27.setText(_translate("MainWindow", "x"))
        self.pi_h.setText(_translate("MainWindow", "1944"))
        self.label_31.setText(_translate("MainWindow", "FrameRate (fps):"))
        self.lineEdit_2.setText(_translate("MainWindow", "15"))
        self.radioButton.setText(_translate("MainWindow", "Use RAW YUV format"))
        self.radioButton_2.setText(_translate("MainWindow", "Use RAW RGB format"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("MainWindow", "HQ PiCamera Settings"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), _translate("MainWindow", "Basler Camera"))
        self.showContinously.setText(_translate("MainWindow", "Show Continously"))
        self.referenceAngle.setText(_translate("MainWindow", "0"))
        self.outputEvery.setText(_translate("MainWindow", "100"))
        self.label_25.setText(_translate("MainWindow", "Save Outputs Every (chunks):"))
        self.saveLifeOutput.setText(_translate("MainWindow", "Save Outputs"))
        self.dont_SaveLifeOutput.setText(_translate("MainWindow", "Do not Save Outputs"))
        self.label_30.setText(_translate("MainWindow", "Show each frame\n"
" for (ms):"))
        self.lineEdit.setText(_translate("MainWindow", "100"))
        self.label_29.setText(_translate("MainWindow", "Set Angle to Consider\n"
"for the Reference (rad):"))
        self.showOnlyOutputted.setText(_translate("MainWindow", "Show Only Outputted"))
        self.showNothing.setText(_translate("MainWindow", "Show Nothing"))
        self.showImagesAngles.setText(_translate("MainWindow", "Plot only Images and angle"))
        self.showAll.setText(_translate("MainWindow", "Plot all results"))
        self.imagesInChunks.setText(_translate("MainWindow", "1"))
        self.label_28.setText(_translate("MainWindow", "Process Images\n"
"In chunks of:"))
        self.label_24.setText(_translate("MainWindow", "Total Frames to Take\n"
" (set 0 for non-stop):"))
        self.totalFrames.setText(_translate("MainWindow", "1000"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_11), _translate("MainWindow", "Life Take Settings"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "Compute Angle Life"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
